### ISSUE TITLE
Add installation and usage instructions to the Readme

### ISSUE THREAD

**Issue by looeee** [DAVFoundation/dav-js#120]
## Expected Behavior

The Readme should include the basic step required to install and setup a new project. 
The most difficult part of connecting with a new project is often the setup, and if there are a list of simple steps to follow that helps new users a lot. 

## Current Behavior

The Readme is not helpful to new users.

## Possible Solution

Two new sections should be added:

1. Installation

2. Usage, or creation of a basic project 

Alternatively, if there is already a document describing these steps elsewhere, the Readme should link to it.

**Comment by TalAter** [comment]
I think we need to distinguish between two types of documents.

1. Documentation that explains how to use `dav-js` to build something.
2. A `CONTRIBUTING.md` document which explains how to get started contributing to and modifying `dav-js` itself.

The first is available in our [developers site](https://developers.dav.network/protocols/vessel-charging/), although it is still lacking a section explaining the basics of how to get started with it.

The second is definitely needed and it would be great if you could create.
