### ISSUE TITLE
Commands "npm run build-browser-dev" fails with webpack error

### ISSUE THREAD

**Issue by looeee** [DAVFoundation/dav-js#121]
## Expected Behavior

The task should proceed without errors.

## Current Behavior

``` bash
ERROR in multi babel-polyfill ./build/SDKFactory.js
Module not found: Error: Can't resolve './build/SDKFactory.js' in '/mnt/d/web/davFoundation/dav-js'
 @ multi babel-polyfill ./build/SDKFactory.js main[1]
```

## Steps to Reproduce (for bugs)

1. `npm run pre-publish` (runs without errors)
2. `npm run post-install` (runs without errors)
3. `npm run build-browser-dev` OR `npm run build-browser-prod` (produces the error)

## Context

I'm trying to set up and learn to use the project for the first time. 

## Your Environment

* Version used: latest master branch
* Environment name and version: Node v10.14.1
* Server type and version: running locally
* Operating System and version: Ubuntu 18.04

**Comment by TalAter** [comment]
For now we have deprecated building `dav-js` for the browser.

The fact that those two npm scripts are still in `package.json` was an oversight. I just removed those two in https://github.com/DAVFoundation/dav-js/commit/32992931a867b3a770733cd4a196a2a1c285e234

**Comment by looeee** [comment]
Ok, that's clear. Thanks for the fast response 👍
