### ISSUE TITLE
No contribute section

### ISSUE THREAD

**Issue by mikey2020** [DAVFoundation/dav-js#13]
## Expected Behavior
There should be a `how to contribute` section to help newcomers to the project get onboard easily

## Possible Solution
I would like to add a `how to contribute` section.

## Context
It has been kind of hard knowing how to contribute since there is no contribute section compared to other open source projects.

**Comment by griffobeid** [comment]
That would be great! Thanks, @mikey2020 :smiley:

**Comment by TalAter** [comment]
That's a great idea @mikey2020 
One caveat, we are just now in the process of rewriting Captain completely.
Please hold off on creating this document as it will become obsolete within days if you make it now.

**Comment by mikey2020** [comment]
ok @TalAter I will hold off until the changes are completed

**Comment by TalAter** [comment]
Now in #120

**Comment by looeee** [comment]
Fixed in #123
