### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [DAVFoundation/dav-js#16]
Hi, I am a graphic designer and I want to contribute by proposing a logo design for the project. If you like and will use it I will give it as a gift and gladly send you the needed files. here is my proposed logo

The design shows the letter C for "captain" and also shows a flying vehicle/drone (pointing left). there's also the diamond shape inside that represents the logic that runs onboard vehicles.

logomark
![captain-01](https://user-images.githubusercontent.com/36028424/38949150-2e61e6a6-4374-11e8-8260-e1d36f369a6c.png)
logotype A
![captain-02](https://user-images.githubusercontent.com/36028424/38949164-364aa592-4374-11e8-8bc9-9c16fa5ec565.png)
logotype B
![captain-03](https://user-images.githubusercontent.com/36028424/38949171-3a530080-4374-11e8-97bc-3045b1e2a3a4.png)

Thanks and best regards,
Tobaloidee

**Comment by TalAter** [comment]
Thank you for taking the time @Tobaloidee 

I really appreciate you taking the time. I also looked at some of the other logos you've contributed to other open source projects. Your commitment and initiative is really cool.

But for this project (dav-js) we will go with a design based on our own brand.

Thank you again for your awesome work 👍
