### ISSUE TITLE
Create tests for `vessel-charging/BidParams` using jest.

### ISSUE THREAD

**Issue by haialaluf** [DAVFoundation/dav-js#18]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### dav-js

This SDK enabled integrating any client side JS and NodeJS code with the DAV Network.

### The Issue

Create tests for `vessel-charging/BidParams` using jest.

You need to create tests to check that the `serialize` and `deserialize` methods work as expected.

Please use the [test file for class `NeedParams`](../blob/master/src/vessel-charging/NeedParams.test.ts) as a basis for your new code.

* Function `serialize` in class `BidParams` must return a JSON object that contains all properties defined in the `BidParams` instance.

* Function `deserialize` in class `BidParams` receives a JSON string and must initialize all the properties of the `BidParams` instance with the values in the JSON string.

```bidParams1.desrialize(bidParams2.serialize()) == bidParams2``` must therefore always be true.

**NOTE: Some names are changed between protocol string representation of instance properties:**
* `location` is internally represented as `{ lat , lon }` but serialized as `{ latitude , longitude }`
* Private properties are internally prefixed with `_` but serialized without the prefix. i.e. `_protocol` becomes `protocol`

### Contributing to dav-js

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open [dav-js GitHub page](https://github.com/DAVFoundation/dav-js) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/dav-js.git`
- [ ] **Code Code Code**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/dav-js](https://github.com/YOUR-USER-NAME/dav-js)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#7`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by Aliciawyse** [comment]
Hello! I'd like to do this.

**Comment by Aliciawyse** [comment]
Any tips on installing jest? I get an error message whether I try `yarn add --dev jest`
 or `npm install --save-dev jest`.

When I run `yarn add --dev jest`, this is the first error message I see. 

```
error /Users/aliciabarrett/dav-js/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/aliciabarrett/dav-js/node_modules/sha3
Output:
module.js:549
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
```

**Comment by Aliciawyse** [comment]
@TalAter any advice for this kind of error?

**Comment by TalAter** [comment]
Hi @Aliciawyse, sorry for the slow response time.

I've had a similar issue a while back... I think it had to do with the `sha3` library (required by `web3`) not supporting node version 10.x. Back then I had to downgrade my machine from node.js v10

But I actually just upgraded back to node.js v10 a few minutes ago just to test it, and it actually worked for me now.

Can you try the following and tell me if anything works?

* Upgrade to the latest node version and try again.
* Try including `sha3` directly: https://github.com/ethereum/web3.js/issues/1634#issuecomment-389262502 and try again
* Try installing node.js v8 and try again.

**Comment by TalAter** [comment]
Also, the project already includes jest, so you don't need to install it.
I just upgraded it to the latest version too, so maybe you'd like to pull the latest changes.

**Comment by Aliciawyse** [comment]
Oh okay, thanks @TalAter! To pull your latest changes, I had to sync my fork with the upstream repository (https://github.com/DAVFoundation/dav-js). Things looks normal now. I tried to push, but couldn't because some tests failed, not sure why but this sorta feels like progress lol.

**Comment by TalAter** [comment]
We have a bunch of tasks running as a pre-push hook. Linting, testing, spell checking, etc.

What failed?

**Comment by TalAter** [comment]
Did you get these errors?

![1__tal_tals-macbook-pro-5____dropbox_mysite_dav_dav-js__zsh_](https://user-images.githubusercontent.com/926653/45549063-1c259980-b82f-11e8-9ec3-4d362dc50f53.jpg)

I just fixed this and pushed the fix (ebfafdc6f79cd7a699cd309f2e1d3e03f7249573).

**Comment by Aliciawyse** [comment]
@TalAter Yep that was it. Thanks! Going to give this another try later today!

**Comment by TalAter** [comment]
I wonder what ended up helping?

**Comment by Aliciawyse** [comment]
Hmm. Well, less tests are failing. Here's what I'm getting so far. 

![image](https://user-images.githubusercontent.com/13841769/45599026-a21e1d80-b9b2-11e8-9197-6d4e6657c438.png)

![image](https://user-images.githubusercontent.com/13841769/45599246-19a17c00-b9b6-11e8-964f-6a026f8f88f5.png)

![image](https://user-images.githubusercontent.com/13841769/45599251-3473f080-b9b6-11e8-9068-95375883589a.png)

![image](https://user-images.githubusercontent.com/13841769/45599267-8157c700-b9b6-11e8-828f-d5e1020132a8.png)

**Comment by TalAter** [comment]
I googled your error and there are some results around that... but I can't really debug that. You'll have to do it on your machine.

It's not an error I'm familiar with.

I am curious though:

![](https://user-images.githubusercontent.com/13841769/45599267-8157c700-b9b6-11e8-828f-d5e1020132a8.png)

How did you get to 30 commits? 😄  Or is that simply from bringing upstream changes?

**Comment by Aliciawyse** [comment]
Yeah, I'm thinking that was from upstream changes I grabbed. I'm not sure. 

Either way, I got rid of my forked version and forked the project again. I'm able to push without running into the errors like before. 

But, I've hit another wall. 

How do I run my test? 

The jest docs https://jestjs.io/docs/en/cli.html offer some options, but none of them work. 

I've tried `jest src/vessel-charging/NeedFilterParams.test.ts` to see if I can run an existing test. I tried `npm test` but get a message that says`Error: no test specified`. I specify a test like `npm test src/vessel-charging/NeedFilterParams.test.ts` and that gets me the same error message.

**Comment by TalAter** [comment]
You can run it with `npm run jest`

**Comment by Aliciawyse** [comment]
Alright, I'm making progress on this. Still trying to understand how to write a test for the deserialize method. Here's what I'm working with so far... https://github.com/Aliciawyse/dav-js/blob/master/src/vessel-charging/BidParams.test.ts

**Comment by Aliciawyse** [comment]
Any tips on getting the deserialize test to pass? 

Here's a snapshot about why my test is failing 

```
- Expected
+ Received
```

```
 -   "manufacturer": "manufacturer_name",
    -   "model": "model_name",
    +   "manufacturer": Array [
    +     5,
    +   ],
    +   "model": Array [
    +     5,
    +   ],
        "neederDavId": "davId",
    -   "price": "100000000000000000",
    -   "provider": "N3m0",
    +   "price": Array [
    +     "100000000000000000",
    +   ],
    +   "protocol": "boat_charging",
    +   "provider": Array [
    +     5,
    +   ],
    +   "ttl": undefined,
    +   "type": "bid",
```

Am I misunderstanding how the deserialize method works?

**Comment by TalAter** [comment]
This seems to be a bug in vessel charging when setting amenities. It not only sets the amenities but also the `manufacturer`, `model`, and `provider` to the value of the `amenities`. I opened a bug for this.

In the meantime, check out my pull request to your fork which removes those bad params - https://github.com/Aliciawyse/dav-js/pull/1

**Comment by Aliciawyse** [comment]
Thank you so much!

**Comment by TalAter** [comment]
Merged 🎆 

Thank you so much for the help @Aliciawyse

**Comment by Aliciawyse** [comment]
lol no thank you! I appreciate all of the feedback and help @TalAter!
