### ISSUE TITLE
Create tests for `ride-hailing/BidParams` using jest.

### ISSUE THREAD

**Issue by haialaluf** [DAVFoundation/dav-js#21]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### dav-js

This SDK enabled integrating any client side JS and NodeJS code with the DAV Network.

### The Issue

Create tests for `ride-hailing/BidParams` using jest.

You need to create tests to check that the `serialize` and `deserialize` methods work as expected.

Please use the [test file for class `NeedParams`](../blob/master/src/vessel-charging/NeedParams.test.ts) as a basis for your new code.

* Function `serialize` in class `BidParams` must return a JSON object that contains all properties defined in the `BidParams` instance.

* Function `deserialize` in class `BidParams` receives a JSON string and must initialize all the properties of the `BidParams` instance with the values in the JSON string.

```bidParams1.desrialize(bidParams2.serialize()) == bidParams2``` must therefore always be true.

**NOTE: Some names are changed between protocol string representation of instance properties:**
* Private properties are internally prefixed with `_` but serialized without the prefix. i.e. `_protocol` becomes `protocol`

### Contributing to dav-js

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open [dav-js GitHub page](https://github.com/DAVFoundation/dav-js) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/dav-js.git`
- [ ] **Code Code Code**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/dav-js](https://github.com/YOUR-USER-NAME/dav-js)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#7`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by VictoriaKuznetsova** [comment]
Hi! I would like to handle this issue

**Comment by mariolo1985** [comment]
Hello @VictoriaKuznetsova it's all yours :smile:

**Comment by VictoriaKuznetsova** [comment]
I have question about type of currentVehicleLocation in BidParams. I can't find a class with that name. Maybe it shoud be interface ILocation?

**Comment by TalAter** [comment]
@VictoriaKuznetsova You spotted a bug 👍 

I just fixed it and pushed the code. It now imports `ILocation`.

**Comment by VictoriaKuznetsova** [comment]
About this note:
location is internally represented as { lat , lon } but serialized as { latitude , longitude }
It doesn't work this way. Function serialize returns { lat , lon } as-is.

Is it by design?

**Comment by TalAter** [comment]
@srfrnk Can you look at @VictoriaKuznetsova 's comment?

**Comment by srfrnk** [comment]
> About this note:
> location is internally represented as { lat , lon } but serialized as { latitude , longitude }
> It doesn't work this way. Function serialize returns { lat , lon } as-is.
> 
> Is it by design?

This was irrelevant - removed it. Nice catch.

**Comment by mariolo1985** [comment]
Great PR @VictoriaKuznetsova! Merged.

**Comment by VictoriaKuznetsova** [comment]
Thank you
