### ISSUE TITLE
Create tests for `vessel-charging/messages/StartingMessageParams` using jest.

### ISSUE THREAD

**Issue by haialaluf** [DAVFoundation/dav-js#28]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### dav-js

This SDK enabled integrating any client side JS and NodeJS code with the DAV Network.

### The Issue

Create tests for `vessel-charging/messages/StartingMessageParams` using jest.

You need to create tests to check that the `serialize` and `deserialize` methods work as expected.

Please use the [test file for class `NeedParams`](../blob/master/src/vessel-charging/NeedParams.test.ts) as a basis for your new code.

* Function `serialize` in class `MessageParams` must return a JSON object that contains all properties defined in the `MessageParams` instance.

* Function `deserialize` in class `MessageParams` receives a JSON string and must initialize all the properties of the `MessageParams` instance with the values in the JSON string.

```messageParams1.desrialize(messageParams2.serialize()) == messageParams2``` must therefore always be true.

**NOTE: Some names are changed between protocol string representation of instance properties:**
* `location` is internally represented as `{ lat , lon }` but serialized as `{ latitude , longitude }`
* Private properties are internally prefixed with `_` but serialized without the prefix. i.e. `_protocol` becomes `protocol`

### Contributing to dav-js

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open [dav-js GitHub page](https://github.com/DAVFoundation/dav-js) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/dav-js.git`
- [ ] **Code Code Code**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/dav-js](https://github.com/YOUR-USER-NAME/dav-js)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#7`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by james-built** [comment]
Hi, can I contribute on this one?

**Comment by ali-ebner** [comment]
I would like to take this!

**Comment by TalAter** [comment]
Thank you @ali-ebner 

Please go ahead 👍

**Comment by TalAter** [comment]
@ali-ebner There was a bug in our code that would have prevented you from completing this issue. The bug has since been resolved. Are you still interested in doing this issue?

**Comment by ali-ebner** [comment]
@TalAter I meant to get in touch with you about the bug. Unfortunately, I am no longer able to do the issue at this time. Apologies!

**Comment by sark01** [comment]
@TalAter, Could I take this one up?

**Comment by mariolo1985** [comment]
Hi @sark01 you certainly can take this issue 😃 

In regards to classes without deserialize tests, we are reviewing them and will most likely open up issues for those. Keep an eye out in the near future 👓 thanks!

**Comment by sark01** [comment]
@TalAter I've been meaning to raise this point. I think its better if I don't consume the rest of the issues as I believe I've kinda figured how to fix them and give the newcomers a chance. I believe contributing to open-source can be daunting at first as it was for me a couple of weeks back. I thank you and the maintainers of this repository for helping me gain a thorough insight into how open-source contributions are made.
Meanwhile, I could try my hand at some newer issues not related to the ones I've fixed.

**Comment by mariolo1985** [comment]
Thanks for the PR @sark01. Great work!

**Comment by TalAter** [comment]
Sounds good @sark01 

Also, now that you have had some experience with the project feel free to suggest other improvements you think should be made.

Thank you for all the help so far 👍
