### ISSUE TITLE
Add serialize test for `src/ride-hailing/NeedFilterParams.test.ts` using Jest (first-timers-only)

### ISSUE THREAD

**Issue by mariolo1985** [DAVFoundation/dav-js#80]
## first-timers-only

This issue is tagged 🕺  **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=first-timers-only+org%3ADAVFoundation+label%3A%22up-for-grabs%22&state=open&type=Issues).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### dav-js

This repo contains the DAV JavaScript SDK. This SDK allows developers to build applications and servers that connect to the DAV network. For example, allowing a drone to find charging stations, or an autonomous car to ask for traffic data.

## How you can help

In order to foster a community that is welcoming for open source contributions, it is important for us to have good test coverage. And good tests are simple, readable tests.

Here is a good opportunity to simplify one of our tests.

### The Issue

We need to add a test for the `serialze()` method in [**src/ride-hailing/NeedFilterParams.test.ts**](../blob/master/src/ride-hailing/NeedFilterParams.test.ts#L32). This test is for **src/ride-hailing/NeedFilterParams.ts**.

Please add a test similar to this:
```javascript
  describe('serialize method', () => {
    it('should return serialized need params object with the current values', () => {
      expect(messageParams.serialize()).toEqual(serializedMessageParams);
    });
  });
```

An example can be found [here](../blob/master/src/ride-hailing/VehicleLocationMessageParams.test.ts#L19).

After making your changes, run `npm run jest` to make sure our tests are passing.

### Contributing to dav-js

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment on this issue that you would like to do it (if you're the first you can start working on it immediately)
- [ ] Open [dav-js GitHub page](https://github.com/DAVFoundation/dav-js) and click the ★ Star and then ⑂ Fork buttons
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/dav-js.git`
- [ ] Install dependencies by running `npm install`
- [ ] Make sure everything is working and all tests pass by running `npm run jest`
- [ ] **Code Code Code**
- [ ] Make sure everything is still working and all tests pass by running `npm run jest` again
- [ ] Commit all your changes
- [ ] Push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/dav-js](https://github.com/YOUR-USER-NAME/dav-js)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#7`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by vincentle** [comment]
@mariolo1985 Can I take this?

**Comment by mariolo1985** [comment]
Hi @vincentle are you still interested in working on this?

**Comment by abdchehadeh** [comment]
I claim it :) @mariolo1985

**Comment by mariolo1985** [comment]
Hi @abdchehadeh it's all yours! Thanks 😄

**Comment by abdchehadeh** [comment]
<pre>
<b>Test Suites: </b><font color="#EF2929"><b>2 failed</b></font>, <font color="#8AE234"><b>33 passed</b></font>, 35 total
<b>Tests:       </b><font color="#FCE94F"><b>23 skipped</b></font>, <font color="#8AE234"><b>114 passed</b></font>, 137 total
<b>Snapshots:   </b>0 total
<b>Time:</b>        16.97s
<font color="#AAAAAA">Ran all test suites.</font>
[<font color="#555753">19:22:04</font>] &apos;<font color="#06989A">jest</font>&apos; <font color="#CC0000">errored after</font> <font color="#75507B">17 s</font>
[<font color="#555753">19:22:04</font>] <font color="#CC0000">Error</font> in plugin &quot;<font color="#06989A">gulp-jest</font>&quot;
</pre>

This is the outcome of 

> npm run jest

is this the current state of the project ?

**Comment by TalAter** [comment]
Thank you @abdchehadeh 👍

Looks great
