### ISSUE TITLE
Update vehicle details in ride-hailing BidParams test (first-timers-only)

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/dav-js#84]
## first-timers-only

This issue is tagged 🕺  **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for writing code that makes drones fly, lets cars find charging stations, helps people and goods get from place to place, and more.

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=first-timers-only+org%3ADAVFoundation+label%3A%22up-for-grabs%22&state=open&type=Issues).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### dav-js

This repo contains the DAV JavaScript SDK. This SDK allows developers to build applications and servers that connect to the DAV network. For example, allowing a drone to find charging stations, or an autonomous car to ask for traffic data.

## How you can help

In order to foster a community that is welcoming for open source contributions, it is important for us to have good test coverage. And good tests are simple, readable tests.

Here is a good opportunity to update one of our tests.

### The Issue

`/src/ride-hailing/BidParams.test.ts` contains a test for the parameters that go into a bid by a vehicle offering to take a passenger. This is most likely going to be a car... however the test currently lists the vehicle details as a drone.

<img width="359" alt="dav-js_bidparams_test_ts_at_master_ _davfoundation_dav-js" src="https://user-images.githubusercontent.com/926653/46760948-f7143180-ccdb-11e8-9852-1d94f6183110.png">

While passenger drones are starting to become a reality, this may be confusing to most developers reading the test.

Update the `vehicle` within the `bidParams` object to be of type `car` and have details which are more "car-like" rather than a drone. A fake company and model would be great :) Something like the Highlander Excursion or something.

After making your changes, run `npm run jest` to make sure our tests are now passing.

### Contributing to dav-js

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment on this issue that you would like to do it (if you're the first you can start working on it immediately)
- [ ] Open [dav-js GitHub page](https://github.com/DAVFoundation/dav-js) and click the ★ Star and then ⑂ Fork buttons
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/dav-js.git`
- [ ] Install dependencies by running `npm install`
- [ ] Make sure everything is working and all tests pass by running `npm run jest`
- [ ] **Code Code Code**
- [ ] Make sure everything is still working and all tests pass by running `npm run jest` again
- [ ] Commit all your changes
- [ ] Push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/dav-js](https://github.com/YOUR-USER-NAME/dav-js)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#7`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by devkant** [comment]
Can i take this?

**Comment by tifa64** [comment]
I'm on it

**Comment by tifa64** [comment]
@devkant 
Yup and finished it:
https://github.com/DAVFoundation/dav-js/pull/85
